version: '3.8'

services:
  wisecow:
    build: .
    ports:
      - "4499:4499"
    environment:
      - PORT=4499
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4499"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M