apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
  labels:
    app: wisecow
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4499"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: wisecow
          image: ghcr.io/anuragstark/wisecow:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "cd /app && exec ./wisecow.sh"]
          ports:
            - containerPort: 4499
              name: http
          env:
            - name: PORT
              value: "4499"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # Startup probe - gives container time to start
          startupProbe:
            httpGet:
              path: /
              port: 4499
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12 # 60 seconds total (12 * 5)
            successThreshold: 1
          # Readiness probe - more lenient during startup
          readinessProbe:
            httpGet:
              path: /
              port: 4499
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          # Liveness probe - only after startup is complete
          livenessProbe:
            httpGet:
              path: /
              port: 4499
              scheme: HTTP
            initialDelaySeconds: 60 # Wait longer for liveness
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          securityContext:
            runAsNonRoot: false # Changed to false temporarily for debugging
            runAsUser: 0 # Run as root temporarily
            capabilities:
              drop: ["ALL"]
      restartPolicy: Always
      securityContext:
        fsGroup: 2000

---
apiVersion: v1
kind: Namespace
metadata:
  name: wisecow
  labels:
    name: wisecow
